Require file size for boost online deal (#311)
Boost online deal requires file size as part of the proposal. Otherwise,
boost will report below error
```
Error: failed to verify CommP: failed to generate CommP: performing local commp: failed to get CARv2 reader: EOF
```

- [x] Making manual deal with boost online deal but without file size
will return error.
- [x] Add external piece to manual deal can now specify the CAR file
size


fixes #297